CREATE TABLE "tesseract_snapshot" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"pair" text NOT NULL,
	"captured_at" timestamp NOT NULL,
	"current_price" double precision,
	"direction" text,
	"signal_side" text,
	"side_conflict" boolean,
	"gauge_score" double precision,
	"gauge_label" text,
	"rr" double precision,
	"atr_value" double precision,
	"entry" double precision,
	"sl" double precision,
	"tp1" double precision,
	"tp2" double precision,
	"drive" double precision,
	"heat" double precision,
	"mass" double precision,
	"flow" double precision,
	"book" double precision,
	"acceptance_direction" text,
	"field_state" text,
	"trend" text,
	"volatility" text,
	"volume" text,
	"trend_strength" double precision,
	"volatility_percentile" double precision,
	"is_choppy" boolean,
	"in_squeeze" boolean,
	"candle_count" integer,
	"raw" jsonb,
	"fwd_15m" double precision,
	"fwd_30m" double precision,
	"fwd_60m" double precision,
	"fwd_240m" double precision,
	"labeled_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "tesseract_snapshot_pair_time_idx" ON "tesseract_snapshot" USING btree ("pair","captured_at");--> statement-breakpoint
CREATE INDEX "tesseract_snapshot_unlabeled_idx" ON "tesseract_snapshot" USING btree ("labeled_at","captured_at");